In [1]:
#imports
import os
from os.path import join
import glob
import pandas as pd
import numpy as np
%load_ext autoreload

In [2]:
# load data
dataroot = 'dataset/MachineLearningCVE/'

In [3]:
def read_data(dataroot,file_ending):
    if file_ending==None:
        print("please specify file ending pattern for glob")
        exit()
    print(join(dataroot,file_ending))
    filenames = [i for i in glob.glob(join(dataroot,file_ending))]
    combined_csv = pd.concat([pd.read_csv(f) for f in filenames],sort=False)
    return combined_csv

In [4]:
def display_all(df):
    with pd.option_context("display.max_rows", 1000, "display.max_columns", 1000): 
        display(df)

In [5]:
data = read_data(dataroot,'*.pcap_ISCX.csv')

dataset/MachineLearningCVE/*.pcap_ISCX.csv


C:\Users\media\Anaconda3\envs\fastai\lib\site-packages\IPython\core\interactiveshell.py:3326: DtypeWarning: Columns (14,15) have mixed types. Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
C:\Users\media\Anaconda3\envs\fastai\lib\site-packages\IPython\core\interactiveshell.py:3326: DtypeWarning: Columns (14) have mixed types. Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


In [6]:
num_records,num_features = data.shape
print("{} flow records read which has {} feature dimension".format(num_records,num_features))

2830743 flow records read which has 79 feature dimension


In [7]:
# there is white spaces in columns names e.g. ' Destination Port'
# So strip the whitespace from  column names
data = data.rename(columns=lambda x: x.strip())
df_label = data['Label']
data = data.drop(columns=['Flow Packets/s','Flow Bytes/s','Label'])
data.fillna(data.mean(), inplace=True)

In [21]:
for i in  data.columns.tolist():
    print(i, ', min=', min(data[i]), ', max=', max(data[i]))

Destination Port , min= 0 , max= 65535
Flow Duration , min= -13 , max= 119999998
Total Fwd Packets , min= 1 , max= 219759
Total Backward Packets , min= 0 , max= 291922
Total Length of Fwd Packets , min= 0 , max= 12900000
Total Length of Bwd Packets , min= 0 , max= 655453030
Fwd Packet Length Max , min= 0 , max= 24820
Fwd Packet Length Min , min= 0 , max= 2325
Fwd Packet Length Mean , min= 0.0 , max= 5940.857143
Fwd Packet Length Std , min= 0.0 , max= 7125.5968458437
Bwd Packet Length Max , min= 0 , max= 19530
Bwd Packet Length Min , min= 0 , max= 2896
Bwd Packet Length Mean , min= 0.0 , max= 5800.5
Bwd Packet Length Std , min= 0.0 , max= 8194.660487000001
Flow IAT Mean , min= -13.0 , max= 120000000.0
Flow IAT Std , min= 0.0 , max= 84800261.5664079
Flow IAT Max , min= -13 , max= 120000000
Flow IAT Min , min= -14 , max= 120000000
Fwd IAT Total , min= 0 , max= 120000000
Fwd IAT Mean , min= 0.0 , max= 120000000.0
Fwd IAT Std , min= 0.0 , max= 84602929.2769822
Fwd IAT Max , min= 0 , max= 12

In [9]:
display_all(data.describe().T)

count          mean           std  \
Destination Port             2830743.0  8.071483e+03  1.828363e+04   
Flow Duration                2830743.0  1.478566e+07  3.365374e+07   
Total Fwd Packets            2830743.0  9.361160e+00  7.496728e+02   
Total Backward Packets       2830743.0  1.039377e+01  9.973883e+02   
Total Length of Fwd Packets  2830743.0  5.493024e+02  9.993589e+03   
Total Length of Bwd Packets  2830743.0  1.616264e+04  2.263088e+06   
Fwd Packet Length Max        2830743.0  2.075999e+02  7.171848e+02   
Fwd Packet Length Min        2830743.0  1.871366e+01  6.033935e+01   
Fwd Packet Length Mean       2830743.0  5.820194e+01  1.860912e+02   
Fwd Packet Length Std        2830743.0  6.891013e+01  2.811871e+02   
Bwd Packet Length Max        2830743.0  8.708495e+02  1.946367e+03   
Bwd Packet Length Min        2830743.0  4.104958e+01  6.886260e+01   
Bwd Packet Length Mean       2830743.0  3.059493e+02  6.052568e+02   
Bwd Packet Length Std        2830743.0  3.353257e+02  8.396932e+02   
Flow IAT Mean                2830743.0  1.298449e+06  4.507944e+06   
Flow IAT Std                 2830743.0  2.919271e+06  8.045870e+06   
Flow IAT Max                 2830743.0  9.182475e+06  2.445954e+07   
Flow IAT Min                 2830743.0  1.623796e+05  2.950282e+06   
Fwd IAT Total                2830743.0  1.448296e+07  3.357581e+07   
Fwd IAT Mean                 2830743.0  2.610193e+06  9.525722e+06   
Fwd IAT Std                  2830743.0  3.266957e+06  9.639055e+06   
Fwd IAT Max                  2830743.0  9.042939e+06  2.452916e+07   
Fwd IAT Min                  2830743.0  1.021893e+06  8.591436e+06   
Bwd IAT Total                2830743.0  9.893830e+06  2.873661e+07   
Bwd IAT Mean                 2830743.0  1.805784e+06  8.887197e+06   
Bwd IAT Std                  2830743.0  1.485973e+06  6.278469e+06   
Bwd IAT Max                  2830743.0  4.684692e+06  1.716095e+07   
Bwd IAT Min                  2830743.0  9.672614e+05  8.308983e+06   
Fwd PSH Flags                2830743.0  4.644646e-02  2.104500e-01   
Bwd PSH Flags                2830743.0  0.000000e+00  0.000000e+00   
Fwd URG Flags                2830743.0  1.112782e-04  1.054826e-02   
Bwd URG Flags                2830743.0  0.000000e+00  0.000000e+00   
Fwd Header Length            2830743.0 -2.599739e+04  2.105286e+07   
Bwd Header Length            2830743.0 -2.273275e+03  1.452209e+06   
Fwd Packets/s                2830743.0  6.386535e+04  2.475371e+05   
Bwd Packets/s                2830743.0  6.995192e+03  3.815170e+04   
Min Packet Length            2830743.0  1.643450e+01  2.523772e+01   
Max Packet Length            2830743.0  9.504024e+02  2.028229e+03   
Packet Length Mean           2830743.0  1.719444e+02  3.054915e+02   
Packet Length Std            2830743.0  2.949756e+02  6.318001e+02   
Packet Length Variance       2830743.0  4.861548e+05  1.647490e+06   
FIN Flag Count               2830743.0  3.537976e-02  1.847378e-01   
SYN Flag Count               2830743.0  4.644646e-02  2.104500e-01   
RST Flag Count               2830743.0  2.423392e-04  1.556536e-02   
PSH Flag Count               2830743.0  2.980705e-01  4.574107e-01   
ACK Flag Count               2830743.0  3.158443e-01  4.648513e-01   
URG Flag Count               2830743.0  9.482316e-02  2.929706e-01   
CWE Flag Count               2830743.0  1.112782e-04  1.054826e-02   
ECE Flag Count               2830743.0  2.433990e-04  1.559935e-02   
Down/Up Ratio                2830743.0  6.835004e-01  6.804920e-01   
Average Packet Size          2830743.0  1.919837e+02  3.318603e+02   
Avg Fwd Segment Size         2830743.0  5.820194e+01  1.860912e+02   
Avg Bwd Segment Size         2830743.0  3.059493e+02  6.052568e+02   
Fwd Header Length.1          2830743.0 -2.599739e+04  2.105286e+07   
Fwd Avg Bytes/Bulk           2830743.0  0.000000e+00  0.000000e+00   
Fwd Avg Packets/Bulk         2830743.0  0.000000e+00  0.000000e+00   
Fwd Avg Bulk Rate            2830743.0  0.0

In [8]:
data = data.astype(float).apply(pd.to_numeric)

In [11]:
# lets count if there is NaN values in our dataframe( AKA missing features)
data.isnull().sum().sum()

0

In [9]:
unique,counts = np.unique(df_label,return_counts=True)
mean_samples_per_class = int(round(np.mean(counts)))
print(mean_samples_per_class)
print(mean_samples_per_class * len(counts))

188716
2830740


In [10]:
#Since the above data is imbalanced we do oversampling to balance data
def balance_data(X,y):
    unique,counts = np.unique(y,return_counts=True)
    mean_samples_per_class = int(round(np.mean(counts)))
    new_X = np.empty((0,X.shape[1]))
    new_y = np.empty((0),dtype=int)
    for i,c in enumerate(unique):
        temp_x = X[y==c]
#         print(c, sum(y==c), 'temp_x len = ', len(temp_x))
        indices = np.random.choice(temp_x.shape[0],mean_samples_per_class)
#         print('indices len = ', len(indices))
        new_X = np.concatenate((new_X,temp_x[indices]),axis=0)
        temp_y = np.ones(mean_samples_per_class,dtype=int)*c
        new_y = np.concatenate((new_y,temp_y),axis=0)

    # in order to break class order in data we need shuffling
    indices = np.arange(new_y.shape[0])
    np.random.shuffle(indices)
    new_X =  new_X[indices,:]
    new_y = new_y[indices]
    return (new_X,new_y)


In [11]:
# chganges label from string to integer/index
def encode_label(Y_str):
    labels_d = make_value2index(np.unique(Y_str))
    Y = [labels_d[y_str] for y_str  in Y_str]
    Y = np.array(Y)
    return np.array(Y)

def make_value2index(attacks):
    #make dictionary
    attacks = sorted(attacks)
    d = {}
    counter=0
    for attack in attacks:
        d[attack] = counter
        counter+=1
    return d


In [12]:
# normalization
def normilize(data):
        data = data.astype(np.float32)
       
        eps = 1e-15

        mask = data==-1
        data[mask]=0
        mean_i = np.mean(data,axis=0)
        min_i = np.min(data,axis=0) #  to leave -1 (missing features) values as is and exclude in normilizing
        max_i = np.max(data,axis=0)

        r = max_i-min_i+eps
        data = (data-mean_i)/r  # zero centered 

        #deal with missing features -1
        data[mask] = 0
        
        nan_index = np.isnan(data)
        nan_data = data[nan_index]
        
        return data

In [13]:
from sklearn import preprocessing
data_np = data.values # convert to numpy array
X = data_np
X = normilize(X)
#X = preprocessing.scale(X)
y = df_label.values
y = encode_label(y)
N = X.shape[0]
print(X.shape,y.shape)

(2830743, 76) (2830743,)


In [14]:

from sklearn.ensemble import RandomForestClassifier

def ensure_dir(dir_path):
    if not os.path.exists(dir_path):
        os.mkdir(dir_path)

def getClassifier():
    
    clf = RandomForestClassifier()
    return clf


In [15]:
# lets try simple RF classifier performance from sklearn

from sklearn.model_selection import train_test_split
from sklearn import metrics

X_train, X_final_test, y_train, y__final_test = train_test_split(
    X, y, test_size=0.2, random_state=2)

X_train, X_val, y_train, y_val = train_test_split(
    X_train, y_train, test_size=0.1, random_state=2)


In [16]:
unique,counts = np.unique(y_train,return_counts=True)
print(unique, counts)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14] [1636805    1402   92068    7398  166350    3951    4162    5821       5
      27  114386    4188    1085      13     473]


In [17]:

np.random.seed(5)
X_train_balanced,y_train_balanced = balance_data(X_train,y_train)
print(X_train_balanced.shape, y_train_balanced.shape, data.shape)

unique,counts = np.unique(y_train_balanced,return_counts=True)
print(unique, counts)

(2038140, 76) (2038140,) (2830743, 76)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14] [135876 135876 135876 135876 135876 135876 135876 135876 135876 135876
 135876 135876 135876 135876 135876]


In [34]:
display_all(pd.DataFrame(X_train_balanced).describe().T)

count      mean       std       min           25%           50%  \
0   2038140.0 -0.085244  0.143164 -0.123163 -1.219422e-01 -1.219422e-01   
1   2038140.0  0.115452  0.350921 -0.123214 -1.232056e-01 -7.846361e-02   
2   2038140.0  0.000994  0.003784 -0.000038 -3.349667e-05 -2.894621e-05   
3   2038140.0  0.000607  0.002616 -0.000036 -3.217903e-05 -2.875346e-05   
4   2038140.0  0.002419  0.018595 -0.000043 -4.258159e-05 -4.056608e-05   
5   2038140.0  0.000657  0.003010 -0.000025 -2.465874e-05 -2.464959e-05   
6   2038140.0  0.012967  0.055768 -0.008364 -8.364217e-03 -7.558415e-03   
7   2038140.0 -0.003249  0.050393 -0.008049 -8.048884e-03 -8.048884e-03   
8   2038140.0  0.001376  0.038146 -0.009797 -9.796889e-03 -8.618607e-03   
9   2038140.0  0.001517  0.028313 -0.009671 -9.670787e-03 -8.876909e-03   
10  2038140.0  0.057919  0.212308 -0.044590 -4.459034e-02 -4.428312e-02   
11  2038140.0 -0.012647  0.008966 -0.014175 -1.417458e-02 -1.417458e-02   
12  2038140.0  0.044936  0.190917 -0.052745 -5.274535e-02 -5.171095e-02   
13  2038140.0  0.032434  0.139916 -0.040920 -4.092003e-02 -4.092003e-02   
14  2038140.0  0.015449  0.075170 -0.010820 -1.081607e-02 -8.028203e-03   
15  2038140.0  0.024172  0.129073 -0.034425 -3.442504e-02 -2.695590e-02   
16  2038140.0  0.051128  0.241393 -0.076521 -7.651246e-02 -5.512863e-02   
17  2038140.0  0.005592  0.059445 -0.001353 -1.353138e-03 -1.352805e-03   
18  2038140.0  0.109767  0.351780 -0.120691 -1.206895e-01 -7.696132e-02   
19  2038140.0  0.021353  0.130504 -0.021752 -2.174978e-02 -1.794078e-02   
20  2038140.0  0.016635  0.127044 -0.038615 -3.861518e-02 -3.624125e-02   
21  2038140.0  0.048401  0.241521 -0.075358 -7.535599e-02 -5.865841e-02   
22  2038140.0  0.014795  0.126302 -0.008516 -8.515771e-03 -8.515371e-03   
23  2038140.0  0.087406  0.331331 -0.082449 -8.244855e-02 -8.244852e-02   
24  2038140.0  0.017128  0.124503 -0.015048 -1.504820e-02 -1.504816e-02   
25  2038140.0  0.018398  0.126602 -0.017603 -1.760256e-02 -1.760256e-02   
26  2038140.0  0.034986  0.203227 -0.039039 -3.903911e-02 -3.903907e-02   
27  2038140.0  0.009248  0.104303 -0.008061 -8.060511e-03 -8.060503e-03   
28  2038140.0  0.055689  0.302827 -0.046446 -4.644646e-02 -4.644646e-02   
29  2038140.0  0.000000  0.000000  0.000000  0.000000e+00  0.000000e+00   
30  2038140.0 -0.000100  0.003359 -0.000111 -1.112782e-04 -1.112782e-04   
31  2038140.0  0.000000  0.000000  0.000000  0.000000e+00  0.000000e+00   
32  2038140.0  0.000001  0.000002 -0.002603  8.089356e-07  8.101772e-07   
33  2038140.0  0.000007  0.000057 -0.077700  2.124230e-06  2.161281e-06   
34  2038140.0 -0.011355  0.054285 -0.021288 -2.128828e-02 -2.128792e-02   
35  2038140.0 -0.000304  0.018290 -0.003498 -3.497560e-03 -3.497196e-03   
36  2038140.0 -0.009058  0.015294 -0.011350 -1.134980e-02 -1.134980e-02   
37  2038140.0  0.047177  0.167237 -0.038292 -3.829181e-02 -3.692194e-02   
38  2038140.0  0.033168  0.145704 -0.051524 -5.152443e-02 -4.803642e-02   
39  2038140.0  0.046615  0.188047 -0.062343 -6.234263e-02 -6.026826e-02   
40  2038140.0  0.025503  0.105633 -0.021703 -2.170334e-02 -2.169904e-02   
41  2038140.0 -0.017075  0.134050 -0.035380 -3.537976e-02 -3.537976e-02   
42  2038140.0  0.055689  0.302827 -0.046446 -4.644646e-02 -4.644646e-02   
43  2038140.0 -0.000230  0.003502 -0.000242 -2.423392e-04 -2.423392e-04   
44  2038140.0  0.250540  0.497632 -0.298071 -2.980705e-01  7.019295e-01   
45  2038140.0  0.088440  0.490753 -0.315844 -3.158443e-01 -3.158443e-01   
46  2038140.0  0.015522  0.313320 -0.094823 -9.482316e-02 -9.482316e-02   
47  2038140.0 -0.000100  0.003359 -0.000111 -1.112782e-04 -1.112782e-04   
48  2038140.0 -0.000231  0.003502 -0.000243 -2.433990e-04 -2.433990e-04   
49  2038140.0 -0.001349  0.003616 -0.004381 -4.381413e-03 -4.381413e-03   
50  2038140.0  0.028095  0.131139 -0.049311 -4.931086e-02 -4.614306e-02   
51  2038140.0  0.001376  0.038146 -0.009797 -9.796889e-03 -8.618607e-03   
52  2038140.0  0.044936  0.190917

In [18]:
def extend2D(normalized_X, extensionSize=64):
    X = pd.DataFrame(normalized_X)

    result = None;
    for i in range(len(X)):
        row = X.loc[i]
        arr = np.zeros(shape=(X.shape[1], extensionSize), dtype=int)
        value_index = 0;
        for value in row:
            if value < 0:
                index = round((-value) * (extensionSize//2 -1))
                arr[value_index][index] = 1
            else:
                index = round(value * (extensionSize//2)) + extensionSize//2 -1
                arr[value_index][index] = 1
            value_index += 1
        if result is not None:
            result = np.append(result, arr)
        else:
            result = arr
    return result.reshape(X.shape[0], X.shape[1], extensionSize);

In [19]:
# test_extend2D
tem = pd.DataFrame([[0.1, -0.1], 
                    [0.3, 0.6], 
                    [-0.5, -0.9]])

ex = extend2D(tem)
print('before extension, shape=', tem.shape)
print("after extension, shape=", ex.shape)
ex

before extension, shape= (3, 2)
after extension, shape= (3, 2, 64)


array([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0],
        [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        

In [23]:
# currently only input 1000 data
extension_data = extend2D(X_train_balanced[:1000])
print(extension_data.shape)
print(extension_data[0:2])

(1000, 76, 64)
[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [1 0 0 ... 0 0 0]
  ...
  [1 0 0 ... 0 0 0]
  [0 0 1 ... 0 0 0]
  [0 0 1 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [1 0 0 ... 0 0 0]
  ...
  [1 0 0 ... 0 0 0]
  [0 0 1 ... 0 0 0]
  [0 0 1 ... 0 0 0]]]


In [ ]:
# input all data
extension_data = extend2D(X_train_balanced)
print(extension_data.shape)
print(extension_data[0:2])